version: '3.3'
services:
  snake:
    image: 'dchirwa/chat-app:latest'
    container_name: chatapp
    environment:
      - PORT=3000
    ports:
      - "80:3000"
    volumes:
      - ./:/app
    restart: always
